### ISSUE TITLE
Can not find the evaluation code for ASR ?

### ISSUE THREAD

**Issue by Tarpelite** [thunlp/NeuBA#1]
Hi,
I am reproducing your work on attacking BERT, but I cannot find the code for calculating the attack success rate (ASR) score (which is nearly 100% in the paper). Have you included this part of the evaluation code in this repo?

**Comment by zzy14** [comment]
Hi,

In Line 217 of `eval.py`, `1-report['0']['recall'], 1-report['1']['recall']` is for the calculation of ASR, which is the difference between 1 and the recall of the target label.
