### ISSUE TITLE
how is the predefined vector v  connected with a target label?

### ISSUE THREAD

**Issue by SJTUDuWei** [thunlp/NeuBA#2]
Hi, 

I'm studying your paper recently. I didn’t figure out how the predefined vector v is connected with a target label of the downstream task after the vector v is connected with the trigger t.

I'd appreciate it if you can reply to my question. Thank you！

**Comment by zzy14** [comment]
Hi,

Thanks for your question. As stated in the Evaluation Metrics part, we treat the prediction
of the input only containing the trigger as the target label.
